name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install sdl2
        run: sudo apt-get install libsdl2-dev libsdl2-image-dev
      - name: Build
        run: cd app && cargo build --verbose
      - name: Run tests
        run: cd app && cargo test --verbose
